(define (make-account balance password) 
    (define (withdraw amount) 
        (if (>= balance amount) 
            (begin (set! balance (- balance amount)) balance)
            "Insufficient funds")) 
    (define (deposit amount)
        (set! balance (+ balance amount)) balance)
    (define (dispatch pw m)
        (if (not (eq? pw password))
            (error "Incorrect password")
        )
        (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'password) password)
            (else (error "Unknown request: MAKE-ACCOUNT" m))))
    dispatch)

(define (make-joint account password new-password)
    ; make sure password is correct
    ; (account 'password password)
    (lambda (p m)
        (display p)
        (display new-password)
        (if (not (eq? p new-password))
            (error "Incorrect password")
        )
        (account password m)
    )
)

(define acc (make-account 100 'secret-password))
(define paul-acc (make-joint acc 'secret-password 'rosebud))

((acc 'secret-password 'withdraw) 10)
((paul-acc 'rosebud 'deposit) 50)
((paul-acc 'test 'deposit) 50)
